export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUST_ROBOTS_FAILED';